# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 836)
        MainWindow.setMinimumSize(QtCore.QSize(100, 62))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.topWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topWidget.sizePolicy().hasHeightForWidth())
        self.topWidget.setSizePolicy(sizePolicy)
        self.topWidget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.topWidget.setToolTip("")
        self.topWidget.setObjectName("topWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnReturn = QtWidgets.QPushButton(self.topWidget)
        self.btnReturn.setMinimumSize(QtCore.QSize(0, 100))
        self.btnReturn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(16)
        self.btnReturn.setFont(font)
        self.btnReturn.setText("")
        self.btnReturn.setObjectName("btnReturn")
        self.horizontalLayout.addWidget(self.btnReturn)
        self.labTitle = QtWidgets.QLabel(self.topWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.labTitle.setFont(font)
        self.labTitle.setToolTip("")
        self.labTitle.setTextFormat(QtCore.Qt.PlainText)
        self.labTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labTitle.setObjectName("labTitle")
        self.horizontalLayout.addWidget(self.labTitle)
        self.btnExit = QtWidgets.QPushButton(self.topWidget)
        self.btnExit.setMinimumSize(QtCore.QSize(0, 100))
        self.btnExit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(16)
        self.btnExit.setFont(font)
        self.btnExit.setToolTipDuration(-1)
        self.btnExit.setText("")
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.gridLayout_5.addWidget(self.topWidget, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_17.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.bt5 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt5.sizePolicy().hasHeightForWidth())
        self.bt5.setSizePolicy(sizePolicy)
        self.bt5.setMinimumSize(QtCore.QSize(250, 180))
        self.bt5.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(19)
        self.bt5.setFont(font)
        self.bt5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt5.setIconSize(QtCore.QSize(40, 40))
        self.bt5.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bt5.setObjectName("bt5")
        self.gridLayout.addWidget(self.bt5, 3, 2, 1, 1)
        self.bt3 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt3.sizePolicy().hasHeightForWidth())
        self.bt3.setSizePolicy(sizePolicy)
        self.bt3.setMinimumSize(QtCore.QSize(250, 180))
        self.bt3.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(19)
        self.bt3.setFont(font)
        self.bt3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt3.setIconSize(QtCore.QSize(40, 40))
        self.bt3.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bt3.setObjectName("bt3")
        self.gridLayout.addWidget(self.bt3, 2, 3, 1, 1)
        self.bt6 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt6.sizePolicy().hasHeightForWidth())
        self.bt6.setSizePolicy(sizePolicy)
        self.bt6.setMinimumSize(QtCore.QSize(250, 180))
        self.bt6.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(19)
        self.bt6.setFont(font)
        self.bt6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt6.setIconSize(QtCore.QSize(40, 40))
        self.bt6.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bt6.setObjectName("bt6")
        self.gridLayout.addWidget(self.bt6, 3, 3, 1, 1)
        self.bt1 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt1.sizePolicy().hasHeightForWidth())
        self.bt1.setSizePolicy(sizePolicy)
        self.bt1.setMinimumSize(QtCore.QSize(250, 180))
        self.bt1.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(19)
        self.bt1.setFont(font)
        self.bt1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt1.setMouseTracking(True)
        self.bt1.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt1.setToolTipDuration(-1)
        self.bt1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt1.setAutoFillBackground(False)
        self.bt1.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.bt1.setIconSize(QtCore.QSize(40, 40))
        self.bt1.setAutoRepeatInterval(100)
        self.bt1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bt1.setArrowType(QtCore.Qt.NoArrow)
        self.bt1.setObjectName("bt1")
        self.gridLayout.addWidget(self.bt1, 3, 1, 1, 1)
        self.bt4 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt4.sizePolicy().hasHeightForWidth())
        self.bt4.setSizePolicy(sizePolicy)
        self.bt4.setMinimumSize(QtCore.QSize(250, 180))
        self.bt4.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(19)
        self.bt4.setFont(font)
        self.bt4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt4.setIconSize(QtCore.QSize(40, 40))
        self.bt4.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bt4.setObjectName("bt4")
        self.gridLayout.addWidget(self.bt4, 2, 2, 1, 1)
        self.bt2 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt2.sizePolicy().hasHeightForWidth())
        self.bt2.setSizePolicy(sizePolicy)
        self.bt2.setMinimumSize(QtCore.QSize(250, 150))
        self.bt2.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(19)
        self.bt2.setFont(font)
        self.bt2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt2.setIconSize(QtCore.QSize(40, 40))
        self.bt2.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.bt2.setObjectName("bt2")
        self.gridLayout.addWidget(self.bt2, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DispLb_2 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DispLb_2.sizePolicy().hasHeightForWidth())
        self.DispLb_2.setSizePolicy(sizePolicy)
        self.DispLb_2.setMinimumSize(QtCore.QSize(650, 480))
        self.DispLb_2.setMaximumSize(QtCore.QSize(16777215, 1500))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(12)
        self.DispLb_2.setFont(font)
        self.DispLb_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DispLb_2.setObjectName("DispLb_2")
        self.gridLayout_3.addWidget(self.DispLb_2, 1, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.line = QtWidgets.QFrame(self.page_3)
        self.line.setGeometry(QtCore.QRect(220, 10, 16, 578))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.DispLb = QtWidgets.QLabel(self.page_3)
        self.DispLb.setGeometry(QtCore.QRect(250, 40, 701, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DispLb.sizePolicy().hasHeightForWidth())
        self.DispLb.setSizePolicy(sizePolicy)
        self.DispLb.setMinimumSize(QtCore.QSize(650, 480))
        self.DispLb.setMaximumSize(QtCore.QSize(16777215, 1500))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(12)
        self.DispLb.setFont(font)
        self.DispLb.setAlignment(QtCore.Qt.AlignCenter)
        self.DispLb.setObjectName("DispLb")
        self.frame = QtWidgets.QFrame(self.page_3)
        self.frame.setGeometry(QtCore.QRect(490, 490, 257, 77))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ShowBt = QtWidgets.QToolButton(self.frame)
        self.ShowBt.setMinimumSize(QtCore.QSize(0, 53))
        self.ShowBt.setObjectName("ShowBt")
        self.horizontalLayout_2.addWidget(self.ShowBt)
        self.StopBt = QtWidgets.QToolButton(self.frame)
        self.StopBt.setMinimumSize(QtCore.QSize(0, 53))
        self.StopBt.setObjectName("StopBt")
        self.horizontalLayout_2.addWidget(self.StopBt)
        self.RecordBt = QtWidgets.QToolButton(self.frame)
        self.RecordBt.setMinimumSize(QtCore.QSize(0, 53))
        self.RecordBt.setObjectName("RecordBt")
        self.horizontalLayout_2.addWidget(self.RecordBt)
        self.exitBt = QtWidgets.QToolButton(self.frame)
        self.exitBt.setMinimumSize(QtCore.QSize(0, 53))
        self.exitBt.setObjectName("exitBt")
        self.horizontalLayout_2.addWidget(self.exitBt)
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setGeometry(QtCore.QRect(11, 11, 201, 438))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnTurn = QtWidgets.QToolButton(self.widget)
        self.btnTurn.setMinimumSize(QtCore.QSize(80, 80))
        self.btnTurn.setIconSize(QtCore.QSize(40, 40))
        self.btnTurn.setObjectName("btnTurn")
        self.gridLayout_2.addWidget(self.btnTurn, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 1, 1, 1)
        self.btnBoo = QtWidgets.QToolButton(self.widget)
        self.btnBoo.setMinimumSize(QtCore.QSize(80, 80))
        self.btnBoo.setIconSize(QtCore.QSize(40, 40))
        self.btnBoo.setObjectName("btnBoo")
        self.gridLayout_2.addWidget(self.btnBoo, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1)
        self.btnLig = QtWidgets.QToolButton(self.widget)
        self.btnLig.setMinimumSize(QtCore.QSize(80, 80))
        self.btnLig.setIconSize(QtCore.QSize(40, 40))
        self.btnLig.setObjectName("btnLig")
        self.gridLayout_2.addWidget(self.btnLig, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.FmRateLCD = QtWidgets.QLCDNumber(self.widget)
        self.FmRateLCD.setMinimumSize(QtCore.QSize(80, 80))
        self.FmRateLCD.setMaximumSize(QtCore.QSize(16777215, 80))
        self.FmRateLCD.setObjectName("FmRateLCD")
        self.gridLayout_2.addWidget(self.FmRateLCD, 0, 0, 1, 1)
        self.btnPeo = QtWidgets.QToolButton(self.widget)
        self.btnPeo.setMinimumSize(QtCore.QSize(80, 80))
        self.btnPeo.setIconSize(QtCore.QSize(40, 40))
        self.btnPeo.setObjectName("btnPeo")
        self.gridLayout_2.addWidget(self.btnPeo, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.page_3)
        self.widget_2.setGeometry(QtCore.QRect(10, 470, 213, 116))
        self.widget_2.setObjectName("widget_2")
        self.radioSld = QtWidgets.QSlider(self.widget_2)
        self.radioSld.setGeometry(QtCore.QRect(10, 20, 41, 22))
        self.radioSld.setOrientation(QtCore.Qt.Horizontal)
        self.radioSld.setObjectName("radioSld")
        self.voiceTbn = QtWidgets.QToolButton(self.widget_2)
        self.voiceTbn.setGeometry(QtCore.QRect(10, 10, 47, 47))
        self.voiceTbn.setMinimumSize(QtCore.QSize(47, 47))
        self.voiceTbn.setObjectName("voiceTbn")
        self.MsgTE = QtWidgets.QTextEdit(self.widget_2)
        self.MsgTE.setGeometry(QtCore.QRect(11, 65, 191, 40))
        self.MsgTE.setMaximumSize(QtCore.QSize(16777215, 40))
        self.MsgTE.setObjectName("MsgTE")
        self.frame_5 = QtWidgets.QFrame(self.widget_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 60, 191, 52))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mapcBox = QtWidgets.QComboBox(self.frame_5)
        self.mapcBox.setMaximumSize(QtCore.QSize(90, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mapcBox.setFont(font)
        self.mapcBox.setObjectName("mapcBox")
        self.mapcBox.addItem("")
        self.mapcBox.addItem("")
        self.horizontalLayout_4.addWidget(self.mapcBox)
        self.mapSure = QtWidgets.QPushButton(self.frame_5)
        self.mapSure.setMaximumSize(QtCore.QSize(50, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mapSure.setFont(font)
        self.mapSure.setObjectName("mapSure")
        self.horizontalLayout_4.addWidget(self.mapSure)
        self.camerackb = QtWidgets.QRadioButton(self.widget_2)
        self.camerackb.setGeometry(QtCore.QRect(50, 10, 115, 19))
        self.camerackb.setObjectName("camerackb")
        self.videockb = QtWidgets.QRadioButton(self.widget_2)
        self.videockb.setGeometry(QtCore.QRect(50, 40, 115, 19))
        self.videockb.setObjectName("videockb")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(240, 490, 90, 53))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.FilePathLE = QtWidgets.QLineEdit(self.page_3)
        self.FilePathLE.setGeometry(QtCore.QRect(240, 510, 200, 21))
        self.FilePathLE.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.FilePathLE.setPalette(palette)
        self.FilePathLE.setObjectName("FilePathLE")
        self.FilePathBt = QtWidgets.QToolButton(self.page_3)
        self.FilePathBt.setGeometry(QtCore.QRect(440, 510, 47, 21))
        self.FilePathBt.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.FilePathBt.setObjectName("FilePathBt")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.Disp_lab3 = QtWidgets.QLabel(self.page_4)
        self.Disp_lab3.setGeometry(QtCore.QRect(230, 10, 721, 501))
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(12)
        self.Disp_lab3.setFont(font)
        self.Disp_lab3.setAlignment(QtCore.Qt.AlignCenter)
        self.Disp_lab3.setObjectName("Disp_lab3")
        self.frame_4 = QtWidgets.QFrame(self.page_4)
        self.frame_4.setGeometry(QtCore.QRect(10, 20, 201, 571))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("方正清刻本悦宋简体")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 3)
        self.RecordListWidget = QtWidgets.QListWidget(self.frame_4)
        self.RecordListWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.RecordListWidget.setObjectName("RecordListWidget")
        self.gridLayout_6.addWidget(self.RecordListWidget, 2, 0, 1, 3)
        self.FilePathBt_2 = QtWidgets.QToolButton(self.frame_4)
        self.FilePathBt_2.setMinimumSize(QtCore.QSize(0, 41))
        self.FilePathBt_2.setObjectName("FilePathBt_2")
        self.gridLayout_6.addWidget(self.FilePathBt_2, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.page_4)
        self.frame_6.setGeometry(QtCore.QRect(436, 510, 301, 81))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ShowBt_3 = QtWidgets.QToolButton(self.frame_6)
        self.ShowBt_3.setMinimumSize(QtCore.QSize(0, 53))
        self.ShowBt_3.setObjectName("ShowBt_3")
        self.horizontalLayout_3.addWidget(self.ShowBt_3)
        self.StopBt_3 = QtWidgets.QToolButton(self.frame_6)
        self.StopBt_3.setMinimumSize(QtCore.QSize(0, 53))
        self.StopBt_3.setObjectName("StopBt_3")
        self.horizontalLayout_3.addWidget(self.StopBt_3)
        self.AgainBt_3 = QtWidgets.QToolButton(self.frame_6)
        self.AgainBt_3.setMinimumSize(QtCore.QSize(0, 53))
        self.AgainBt_3.setObjectName("AgainBt_3")
        self.horizontalLayout_3.addWidget(self.AgainBt_3)
        self.line_3 = QtWidgets.QFrame(self.page_4)
        self.line_3.setGeometry(QtCore.QRect(210, 20, 20, 581))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page_5)
        self.calendarWidget.setGeometry(QtCore.QRect(510, 40, 431, 511))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(182, 190, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(182, 190, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.calendarWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(False)
        font.setWeight(50)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.frame_11 = QtWidgets.QFrame(self.page_5)
        self.frame_11.setGeometry(QtCore.QRect(110, 20, 281, 91))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.weatiplab = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.weatiplab.setFont(font)
        self.weatiplab.setText("")
        self.weatiplab.setAlignment(QtCore.Qt.AlignCenter)
        self.weatiplab.setObjectName("weatiplab")
        self.gridLayout_7.addWidget(self.weatiplab, 1, 0, 1, 2)
        self.searchWeather = QtWidgets.QPushButton(self.frame_11)
        self.searchWeather.setMinimumSize(QtCore.QSize(0, 32))
        self.searchWeather.setText("")
        self.searchWeather.setObjectName("searchWeather")
        self.gridLayout_7.addWidget(self.searchWeather, 0, 1, 1, 1)
        self.weatherLineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.weatherLineEdit.setMinimumSize(QtCore.QSize(120, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(182, 182, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(182, 182, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.weatherLineEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weatherLineEdit.setFont(font)
        self.weatherLineEdit.setObjectName("weatherLineEdit")
        self.gridLayout_7.addWidget(self.weatherLineEdit, 0, 0, 1, 1)
        self.citinamelab = QtWidgets.QLabel(self.page_5)
        self.citinamelab.setGeometry(QtCore.QRect(20, 130, 411, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.citinamelab.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.citinamelab.setFont(font)
        self.citinamelab.setAlignment(QtCore.Qt.AlignCenter)
        self.citinamelab.setObjectName("citinamelab")
        self.temlab = QtWidgets.QLabel(self.page_5)
        self.temlab.setGeometry(QtCore.QRect(20, 200, 411, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.temlab.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(40)
        self.temlab.setFont(font)
        self.temlab.setAlignment(QtCore.Qt.AlignCenter)
        self.temlab.setObjectName("temlab")
        self.wealab = QtWidgets.QLabel(self.page_5)
        self.wealab.setGeometry(QtCore.QRect(10, 430, 421, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.wealab.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.wealab.setFont(font)
        self.wealab.setAlignment(QtCore.Qt.AlignCenter)
        self.wealab.setObjectName("wealab")
        self.weaLabel = QtWidgets.QLabel(self.page_5)
        self.weaLabel.setGeometry(QtCore.QRect(300, 380, 131, 131))
        self.weaLabel.setMinimumSize(QtCore.QSize(131, 131))
        self.weaLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.weaLabel.setText("")
        self.weaLabel.setObjectName("weaLabel")
        self.calendarWidget.raise_()
        self.frame_11.raise_()
        self.citinamelab.raise_()
        self.temlab.raise_()
        self.weaLabel.raise_()
        self.wealab.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.music_label = QtWidgets.QLabel(self.page_6)
        self.music_label.setGeometry(QtCore.QRect(200, 10, 730, 510))
        self.music_label.setText("")
        self.music_label.setObjectName("music_label")
        self.frame_3 = QtWidgets.QFrame(self.page_6)
        self.frame_3.setGeometry(QtCore.QRect(0, 490, 181, 90))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.next_button = QtWidgets.QToolButton(self.frame_3)
        self.next_button.setGeometry(QtCore.QRect(130, 30, 47, 47))
        self.next_button.setObjectName("next_button")
        self.play_button = QtWidgets.QToolButton(self.frame_3)
        self.play_button.setGeometry(QtCore.QRect(63, 20, 60, 60))
        self.play_button.setObjectName("play_button")
        self.preview_button = QtWidgets.QToolButton(self.frame_3)
        self.preview_button.setGeometry(QtCore.QRect(10, 30, 47, 47))
        self.preview_button.setObjectName("preview_button")
        self.musicListWidget = QtWidgets.QListWidget(self.page_6)
        self.musicListWidget.setGeometry(QtCore.QRect(10, 60, 171, 411))
        self.musicListWidget.setObjectName("musicListWidget")
        self.open_button = QtWidgets.QPushButton(self.page_6)
        self.open_button.setGeometry(QtCore.QRect(60, 0, 51, 51))
        self.open_button.setText("")
        self.open_button.setObjectName("open_button")
        self.frame_2 = QtWidgets.QFrame(self.page_6)
        self.frame_2.setGeometry(QtCore.QRect(195, 530, 711, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label1 = QtWidgets.QLabel(self.frame_2)
        self.label1.setObjectName("label1")
        self.horizontalLayout_6.addWidget(self.label1)
        self.slider = QtWidgets.QSlider(self.frame_2)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout_6.addWidget(self.slider)
        self.label2 = QtWidgets.QLabel(self.frame_2)
        self.label2.setObjectName("label2")
        self.horizontalLayout_6.addWidget(self.label2)
        self.cmb = QtWidgets.QComboBox(self.frame_2)
        self.cmb.setMinimumSize(QtCore.QSize(0, 36))
        self.cmb.setMaximumSize(QtCore.QSize(73, 16777215))
        self.cmb.setObjectName("cmb")
        self.cmb.addItem("")
        self.cmb.setItemText(0, "")
        self.cmb.addItem("")
        self.cmb.addItem("")
        self.cmb.addItem("")
        self.horizontalLayout_6.addWidget(self.cmb)
        self.voiceSld = QtWidgets.QSlider(self.page_6)
        self.voiceSld.setGeometry(QtCore.QRect(920, 460, 16, 71))
        self.voiceSld.setOrientation(QtCore.Qt.Vertical)
        self.voiceSld.setObjectName("voiceSld")
        self.voicebtlabel = QtWidgets.QToolButton(self.page_6)
        self.voicebtlabel.setGeometry(QtCore.QRect(910, 540, 32, 32))
        self.voicebtlabel.setObjectName("voicebtlabel")
        self.musictip = QtWidgets.QLabel(self.page_6)
        self.musictip.setGeometry(QtCore.QRect(20, 70, 151, 31))
        self.musictip.setText("")
        self.musictip.setObjectName("musictip")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.SetStackedWidget = QtWidgets.QStackedWidget(self.page_7)
        self.SetStackedWidget.setGeometry(QtCore.QRect(150, 90, 671, 441))
        self.SetStackedWidget.setObjectName("SetStackedWidget")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.frame_9 = QtWidgets.QFrame(self.page_8)
        self.frame_9.setGeometry(QtCore.QRect(-10, 170, 441, 251))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.bt11 = QtWidgets.QToolButton(self.frame_9)
        self.bt11.setGeometry(QtCore.QRect(10, 40, 191, 81))
        self.bt11.setMinimumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bt11.setFont(font)
        self.bt11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt11.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.bt11.setObjectName("bt11")
        self.bt22 = QtWidgets.QToolButton(self.frame_9)
        self.bt22.setGeometry(QtCore.QRect(230, 40, 190, 80))
        self.bt22.setMinimumSize(QtCore.QSize(160, 80))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bt22.setFont(font)
        self.bt22.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt22.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.bt22.setObjectName("bt22")
        self.bt33 = QtWidgets.QToolButton(self.frame_9)
        self.bt33.setGeometry(QtCore.QRect(10, 130, 190, 80))
        self.bt33.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bt33.setFont(font)
        self.bt33.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt33.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.bt33.setObjectName("bt33")
        self.bt44 = QtWidgets.QToolButton(self.frame_9)
        self.bt44.setGeometry(QtCore.QRect(230, 130, 190, 80))
        self.bt44.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bt44.setFont(font)
        self.bt44.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt44.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.bt44.setObjectName("bt44")
        self.SetStackedWidget.addWidget(self.page_8)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.frame_12 = QtWidgets.QFrame(self.page_10)
        self.frame_12.setGeometry(QtCore.QRect(100, 20, 491, 71))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.FontCbx = QtWidgets.QFontComboBox(self.frame_12)
        self.FontCbx.setMinimumSize(QtCore.QSize(0, 35))
        self.FontCbx.setObjectName("FontCbx")
        self.horizontalLayout_8.addWidget(self.FontCbx)
        self.FontSure = QtWidgets.QPushButton(self.frame_12)
        self.FontSure.setMinimumSize(QtCore.QSize(0, 35))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.FontSure.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FontSure.setFont(font)
        self.FontSure.setObjectName("FontSure")
        self.horizontalLayout_8.addWidget(self.FontSure)
        self.frame_13 = QtWidgets.QFrame(self.page_10)
        self.frame_13.setGeometry(QtCore.QRect(80, 120, 511, 61))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame_13)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.colorCbx = QtWidgets.QComboBox(self.frame_13)
        self.colorCbx.setMinimumSize(QtCore.QSize(279, 35))
        self.colorCbx.setObjectName("colorCbx")
        self.colorCbx.addItem("")
        self.colorCbx.addItem("")
        self.colorCbx.addItem("")
        self.horizontalLayout_9.addWidget(self.colorCbx)
        self.ColorSure = QtWidgets.QPushButton(self.frame_13)
        self.ColorSure.setMinimumSize(QtCore.QSize(0, 35))
        self.ColorSure.setMaximumSize(QtCore.QSize(93, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.ColorSure.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ColorSure.setFont(font)
        self.ColorSure.setObjectName("ColorSure")
        self.horizontalLayout_9.addWidget(self.ColorSure)
        self.frame_14 = QtWidgets.QFrame(self.page_10)
        self.frame_14.setGeometry(QtCore.QRect(100, 210, 351, 46))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.frame_14)
        self.label_11.setMinimumSize(QtCore.QSize(130, 35))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.fontSizeSld = QtWidgets.QSlider(self.frame_14)
        self.fontSizeSld.setMinimumSize(QtCore.QSize(0, 35))
        self.fontSizeSld.setMinimum(12)
        self.fontSizeSld.setMaximum(30)
        self.fontSizeSld.setOrientation(QtCore.Qt.Horizontal)
        self.fontSizeSld.setTickInterval(2)
        self.fontSizeSld.setObjectName("fontSizeSld")
        self.horizontalLayout_10.addWidget(self.fontSizeSld)
        self.SetStackedWidget.addWidget(self.page_10)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.helpStackedWidget = QtWidgets.QStackedWidget(self.page_9)
        self.helpStackedWidget.setGeometry(QtCore.QRect(0, 110, 671, 371))
        self.helpStackedWidget.setObjectName("helpStackedWidget")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_11)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 0, 651, 331))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.helpStackedWidget.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_12)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 0, 651, 331))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.helpStackedWidget.addWidget(self.page_12)
        self.frame_10 = QtWidgets.QFrame(self.page_9)
        self.frame_10.setGeometry(QtCore.QRect(160, 0, 338, 86))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bt222 = QtWidgets.QPushButton(self.frame_10)
        self.bt222.setMinimumSize(QtCore.QSize(100, 62))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.bt222.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bt222.setFont(font)
        self.bt222.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt222.setObjectName("bt222")
        self.horizontalLayout_7.addWidget(self.bt222)
        self.bt111 = QtWidgets.QPushButton(self.frame_10)
        self.bt111.setMinimumSize(QtCore.QSize(100, 62))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.bt111.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bt111.setFont(font)
        self.bt111.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt111.setObjectName("bt111")
        self.horizontalLayout_7.addWidget(self.bt111)
        self.bt333 = QtWidgets.QPushButton(self.frame_10)
        self.bt333.setMinimumSize(QtCore.QSize(100, 62))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.bt333.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bt333.setFont(font)
        self.bt333.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.bt333.setObjectName("bt333")
        self.horizontalLayout_7.addWidget(self.bt333)
        self.SetStackedWidget.addWidget(self.page_9)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.updatbt = QtWidgets.QPushButton(self.page_13)
        self.updatbt.setGeometry(QtCore.QRect(10, 380, 641, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.updatbt.setFont(font)
        self.updatbt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updatbt.setObjectName("updatbt")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_13)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 641, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.SetStackedWidget.addWidget(self.page_13)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_14)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 10, 631, 411))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.SetStackedWidget.addWidget(self.page_14)
        self.subtitle = QtWidgets.QLabel(self.page_7)
        self.subtitle.setGeometry(QtCore.QRect(300, 40, 361, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.subtitle.setFont(font)
        self.subtitle.setText("")
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.setpic = QtWidgets.QLabel(self.page_7)
        self.setpic.setGeometry(QtCore.QRect(530, 10, 381, 611))
        self.setpic.setText("")
        self.setpic.setObjectName("setpic")
        self.setRe = QtWidgets.QToolButton(self.page_7)
        self.setRe.setGeometry(QtCore.QRect(120, 100, 30, 30))
        self.setRe.setObjectName("setRe")
        self.setpic.raise_()
        self.SetStackedWidget.raise_()
        self.subtitle.raise_()
        self.setRe.raise_()
        self.stackedWidget.addWidget(self.page_7)
        self.gridLayout_5.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.SetStackedWidget.setCurrentIndex(3)
        self.helpStackedWidget.setCurrentIndex(0)
        self.btnExit.clicked.connect(MainWindow.close)
        self.voicebtlabel.clicked.connect(self.voiceSld.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnReturn.setToolTip(_translate("MainWindow", "返回主界面"))
        self.labTitle.setText(_translate("MainWindow", "    司南驾驶系统"))
        self.btnExit.setToolTip(_translate("MainWindow", "退出程序"))
        self.label_17.setText(_translate("MainWindow", "Copyright© 2019 SYSU SEIT.All Rights Reserved."))
        self.bt5.setToolTip(_translate("MainWindow", "音乐"))
        self.bt5.setText(_translate("MainWindow", "音乐"))
        self.bt3.setToolTip(_translate("MainWindow", "行车记录"))
        self.bt3.setText(_translate("MainWindow", "行车记录"))
        self.bt6.setToolTip(_translate("MainWindow", "设置"))
        self.bt6.setText(_translate("MainWindow", "设置"))
        self.bt1.setToolTip(_translate("MainWindow", "天气查询", "daohang"))
        self.bt1.setText(_translate("MainWindow", "天气"))
        self.bt4.setToolTip(_translate("MainWindow", "安全驾驶"))
        self.bt4.setText(_translate("MainWindow", "安全驾驶"))
        self.bt2.setToolTip(_translate("MainWindow", "相机校正"))
        self.bt2.setText(_translate("MainWindow", "相机校正"))
        self.DispLb_2.setText(_translate("MainWindow", "请矫正摄像头:)"))
        self.label_3.setText(_translate("MainWindow", "            请调整摄像头使水平线接近地平面，并把摄像头放置在车头中央位置，使得铅垂线位于车道正中间"))
        self.DispLb.setText(_translate("MainWindow", "显示实时视频:P"))
        self.ShowBt.setText(_translate("MainWindow", "开始"))
        self.StopBt.setText(_translate("MainWindow", "暂停"))
        self.RecordBt.setText(_translate("MainWindow", "保存"))
        self.exitBt.setText(_translate("MainWindow", "结束"))
        self.btnTurn.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "碰撞预警"))
        self.btnBoo.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "车道偏离"))
        self.btnLig.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "交通灯"))
        self.btnPeo.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "帧率"))
        self.label_6.setText(_translate("MainWindow", "行人"))
        self.voiceTbn.setText(_translate("MainWindow", "..."))
        self.MsgTE.setToolTip(_translate("MainWindow", "提示框"))
        self.mapcBox.setItemText(0, _translate("MainWindow", "百度地图"))
        self.mapcBox.setItemText(1, _translate("MainWindow", "高德地图"))
        self.mapSure.setText(_translate("MainWindow", "确定"))
        self.camerackb.setText(_translate("MainWindow", "摄像头"))
        self.videockb.setText(_translate("MainWindow", "测试视频"))
        self.label_4.setText(_translate("MainWindow", "视频保存路径"))
        self.FilePathBt.setToolTip(_translate("MainWindow", "选择保存路径"))
        self.FilePathBt.setText(_translate("MainWindow", "..."))
        self.Disp_lab3.setText(_translate("MainWindow", "查看记录显示的视频:D"))
        self.label_10.setText(_translate("MainWindow", "行车记录"))
        self.FilePathBt_2.setToolTip(_translate("MainWindow", "选择文件夹"))
        self.FilePathBt_2.setText(_translate("MainWindow", "..."))
        self.ShowBt_3.setText(_translate("MainWindow", "播放"))
        self.StopBt_3.setText(_translate("MainWindow", "暂停"))
        self.AgainBt_3.setText(_translate("MainWindow", "重播"))
        self.searchWeather.setToolTip(_translate("MainWindow", "查询"))
        self.weatherLineEdit.setText(_translate("MainWindow", "请输入城市名称"))
        self.citinamelab.setText(_translate("MainWindow", "城市名"))
        self.temlab.setText(_translate("MainWindow", "气温"))
        self.wealab.setText(_translate("MainWindow", "天气"))
        self.next_button.setText(_translate("MainWindow", "..."))
        self.play_button.setText(_translate("MainWindow", "..."))
        self.preview_button.setText(_translate("MainWindow", "..."))
        self.label1.setText(_translate("MainWindow", "00:00"))
        self.label2.setText(_translate("MainWindow", "00:00"))
        self.cmb.setItemText(1, _translate("MainWindow", "顺序播放"))
        self.cmb.setItemText(2, _translate("MainWindow", "单曲循环"))
        self.cmb.setItemText(3, _translate("MainWindow", "随机播放"))
        self.voicebtlabel.setText(_translate("MainWindow", "..."))
        self.bt11.setText(_translate("MainWindow", "个性化设置"))
        self.bt22.setText(_translate("MainWindow", "帮助中心"))
        self.bt33.setText(_translate("MainWindow", "开发者信息"))
        self.bt44.setText(_translate("MainWindow", "更新"))
        self.label_9.setText(_translate("MainWindow", "字体"))
        self.FontSure.setText(_translate("MainWindow", "确定"))
        self.label_2.setText(_translate("MainWindow", "模式设置"))
        self.colorCbx.setItemText(0, _translate("MainWindow", "白天模式"))
        self.colorCbx.setItemText(1, _translate("MainWindow", "黑夜模式"))
        self.colorCbx.setItemText(2, _translate("MainWindow", "护眼模式"))
        self.ColorSure.setText(_translate("MainWindow", "确定"))
        self.label_11.setText(_translate("MainWindow", "字号"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">司南驾驶系统是一个辅助驾驶软件，该系统在行车时利用摄像头捕捉周围画面，收集数据，对物体进行辨识与追踪，并给予驾驶员危险预警或提醒，有效增加了汽车驾驶的舒适性安全性。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">司南驾驶系统分为6个模块，分别是功能演示、安全驾驶、行车记录、天气查询、音乐播放、设置。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">功能演示模块能够帮助用户了解软件的基本功能，进入后可以选择我们提供的演示视频了解司南驾驶系统的主要功能。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">安全驾驶模块为用户提供了实时检测功能，视频输入方式用户可以选择摄像头输入（正常使用）或者软件模拟输入方式（测试用）。主要功能有提醒和预警，还可以实时录制行车记录。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">行车记录模块可以将安全驾驶模块实时录制的行车记录调出来回看。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">天气查询模块提供了天气查询以及日历查看的功能。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">音乐模块提供了车载音乐的播放功能。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">设置功能模块提供了主题设置，字体选择，查看开发者信息、版本信息等功能。</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.bt222.setText(_translate("MainWindow", "功能介绍"))
        self.bt111.setText(_translate("MainWindow", "应用介绍"))
        self.bt333.setText(_translate("MainWindow", "未完待续"))
        self.updatbt.setText(_translate("MainWindow", "更    新"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">当前版本v1.0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">船新版本，敬请期待</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#00007f;\">开发者信息：</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#00007f;\">中山大学 电子与信息工程学院</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#00007f;\">陈珺鑫——</span><span style=\" font-size:14pt; color:#00007f;\">“哈哈哈哈哈哈”</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#00007f;\">苏俊燊——</span><span style=\" font-size:14pt; color:#00007f;\">“系统原名：贪玩系统”</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#00007f;\">朱铭箴——</span><span style=\" font-size:14pt; color:#00007f;\">“祝大家食用愉快:)”</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.setRe.setToolTip(_translate("MainWindow", "返回设置界面"))
        self.setRe.setText(_translate("MainWindow", "..."))

